import Head from "next/head"
import {
  UserCircleIcon,
  ViewGridIcon,
  MicrophoneIcon,
} from "@heroicons/react/solid"
import { SearchIcon } from "@heroicons/react/outline"
import Image from "next/image"
import Footer from "../components/Footer"
import { useRef } from "react"
import { useRouter } from "next/dist/client/router"

export default function Home() {
  const searchInput = useRef()
  const router = useRouter()

  const handleSearch = (e) => {
    e.preventDefault()

    const term = searchInput.current.value

    if (!term) return
    router.push(`/search?term=${term}`)
  }

  return (
    <div className="flex flex-col justify-center items-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/google-icon.ico" />
      </Head>

      {/* Header */}
      <header className="flex text-sm capitalize justify-between w-full text-gray-700 p-4">
        {/* left */}
        <div className=" flex space-x-4 items-center">
          <p className="link">about</p>
          <p className="link">store</p>
        </div>
        {/* right */}
        <div className=" flex space-x-4 items-center">
          <p className="link">gmail</p>
          <p className="link">Images</p>
          <ViewGridIcon className="h-10 rounded-full p-2 cursor-pointer hover:bg-gray-100" />
          <UserCircleIcon className="text-indigo-700 transition duration-150 transform hover:scale-125 cursor-pointer h-10" />
        </div>
        {/* Icons */}
      </header>
      {/* Body */}
      <form className="flex flex-col items-center mt-44 flex-grow w-4/5 ">
        <Image
          src={
            "https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          }
          height={100}
          width={300}
        />
        <div className="flex w-full focus-within:shadow-lg hover:shadow-lg  mt-5 max-w-md p-3 px-5 border border-gray-200 rounded-full sm:max-w-lg lg:max-w-2xl">
          <SearchIcon className="h-5 mr-4 text-gray-500" />
          <input
            ref={searchInput}
            type="text"
            className="w-full focus:outline-none flex-grow"
          />
          <MicrophoneIcon className="h-5 ml-4" />
        </div>
        <div className="flex flex-col space-y-2 w-1/2 justify-center mt-8 sm:flex-row sm:space-y-0 spacr-x-4">
          <button onClick={handleSearch} className="btn">
            Google Search
          </button>
          <button onClick={handleSearch} className="btn">
            I'm Feeling Lucky
          </button>
        </div>
      </form>
      {/* Footer */}
      <Footer />
    </div>
  )
}
