import Header from "../components/Header"
import Head from "next/head"
import { useRouter } from "next/dist/client/router"
import SearchResults from "../components/SearchResults"

const Search = ({ data }) => {
  const router = useRouter()
  return (
    <div>
      <Head>
        <title>{router.query.term} - Google search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/google-icon.ico" />
      </Head>

      <Header />
      {/* Search Result */}
      <SearchResults data={data} />
    </div>
  )
}

export default Search

// API keys https://developers.google.com/custom-search/v1/using_rest
// Context keys - https://cse.google.com/cse/create/new

export async function getServerSideProps(context) {
  const startIndex = context.query.start || "0"
  const data = await fetch(
    `https://customsearch.googleapis.com/customsearch/v1?cx=${process.env.CONTEXT_KEY}&key=${process.env.API_KEY}&q=${context.query.term}&start=${startIndex}`
  ).then((res) => res.json())

  return {
    props: {
      data,
    },
  }
}
